### ISSUE TITLE
How to pass args to database engine/driver

### ISSUE THREAD

**Issue by juancarlospaco** [aachurin/apistar_peewee#3]
Hello, I have this as arguments for postgresql:

```python
db = PooledPostgresqlExtDatabase("somedatabase",
                                 fields={'varchar': 'varchar'},  # dict of db_field to database column type.
                                 register_hstore=False)         # Mongo-like Key/Value fields.
```

How to pass this arguments using `apistar_peewee`, its not on the `README` docs.

BTW Does [`test_database( )`](http://docs.peewee-orm.com/en/latest/peewee/playhouse.html?highlight=test_database#test_database) works the same right?.

---

Thanks, this module rulez!. :smirk_cat:

**Comment by aachurin** [comment]
Hi!  Like this:
```python
settings = {
    'DATABASE': {
        'default': {
            ...,
            'engine': 'PooledPostgresqlExtDatabase',
            'fields': {'varchar': 'varchar'},
            'register_hstore': false
        }
    }
}
```

**Comment by aachurin** [comment]
I'll think about test_database

**Comment by juancarlospaco** [comment]
Oh thanks!!!, this is kind of answered, I will close it, thanks.

I think `test_database()` should work using the DB directly as in the README, 
but I didnt try, maybe a `test_database()` example on README will be cool.
