### ISSUE TITLE
Peewee 3 Compatibility

### ISSUE THREAD

**Issue by juancarlospaco** [aachurin/apistar_peewee#5]
http://docs.peewee-orm.com/en/latest/peewee/changes.html#changes

I think some changes to make it work with 3.x versions may be needed.

Mainly because of: 
> `BaseModel` has been renamed to `ModelBase`
> Accessing raw model data is now done using `__data__` instead of `_data`

http://docs.peewee-orm.com/en/latest/peewee/changes.html#models

:thinking:

**Comment by aachurin** [comment]
In 1-2 days.

**Comment by aachurin** [comment]
New 0.2 alpha in master. 
I need to resolve some issues before release.

**Comment by aachurin** [comment]
>= 0.2 is not compatible with peewee < 3.0.0

**Comment by juancarlospaco** [comment]
I think its Ok if new version is not compatible with old versions, since all mayor versions can break legacy api, and Peewee itself does the same anyways...

Awesome job BTW. :smile_cat: :+1:
